target("BlinnPhong")
    set_kind("binary")
    add_includedirs("../src/")
    add_headerfiles("./*.h")
    add_deps("OpenGLFramework")
    add_files("BlinnPhong.cpp")

target("ShadowMap")
    set_kind("binary")
    add_includedirs("../src/")
    add_headerfiles("./*.h")
    add_deps("OpenGLFramework")
    add_files("ShadowMap.cpp")

target("SoftShadow")
    set_kind("binary")
    add_includedirs("../src/")
    add_headerfiles("./*.h")
    add_deps("OpenGLFramework")
    add_files("SoftShadow.cpp")

target("BasicFilters")
    set_kind("binary")
    add_includedirs("../src/")
    add_headerfiles("./*.h")
    add_deps("OpenGLFramework")
    add_files("BasicFilters.cpp")

includes("complex-examples")